# Generated by Django 3.1.5 on 2021-01-28 20:36

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('exercise_start', models.DateTimeField(default=datetime.datetime.now)),
                ('scenario_start', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.CharField(default=1, max_length=2)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), srid=4326)),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('page_display_name', models.CharField(default='FORD TRANSIT VAN', max_length=200)),
                ('message_delivery_type', models.CharField(default='FTV', max_length=200)),
                ('message_country_code', models.CharField(default='XXX', max_length=10)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='world.worldborder')),
                ('scenario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_weight', models.FloatField(default=0)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0, srid=4326), srid=4326)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('message_country_code', models.CharField(default='XXX', max_length=10)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scenarios.shipment')),
            ],
        ),
    ]
